name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -U pip
      - run: pip install -r requirements.txt
      - run: ruff check .
      - run: mypy src
      - run: pytest
      - run: python -m build
      - name: Smoke API
        run: |
          python -m uvicorn cognitive_load_detector.api:app --host 0.0.0.0 --port 8000 &
          sleep 3
          curl -f http://127.0.0.1:8000/health
          curl -s -X POST http://127.0.0.1:8000/simulate \
            -H 'content-type: application/json' \
            -d '{"rounds": 2, "num_peers": 3, "samples_per_peer": 64, "batch_size": 16, "num_features": 4}'
          pkill -f "uvicorn"
