name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - run: pip install -e ".[dev]"
      - run: ruff check .
      - run: mypy src || true
      - run: pytest -q --disable-warnings --maxfail=1 --cov=src --cov-report=term-missing
      - run: python -m build
      - name: Smoke API
        run: |
          uvicorn src.app:app --host 127.0.0.1 --port 8000 &
          sleep 3
          python - <<'PY'
import httpx, sys, time
for _ in range(5):
    try:
        response = httpx.get("http://127.0.0.1:8000/health", timeout=5)
        if response.status_code == 200:
            sys.exit(0)
    except Exception:
        time.sleep(1)
sys.exit(1)
PY
